# Generated by Django 2.1 on 2020-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=100, verbose_name='Stream name')),
                ('company', models.CharField(max_length=100, verbose_name='Company name')),
                ('year', models.CharField(max_length=100, verbose_name='year')),
            ],
        ),
    ]
